global:
  pattern: xray

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  datacenter:
    cloudProvider: PROVIDE_CLOUDPROVIDER
    storageClassName: PROVIDE_STORAGECLASS_NAME
    region: PROVIDE_REGION
    clustername: PROVIDE_CLUSTERNAME
    domain: PROVIDE_DOMAIN

  xraylab:
    namespace: "xraylab-1"

    s3:
      # Values for S3 bucket access
      # bucketSource: "provide s3 bucket name where images are stored"
      bucketSource: validated-patterns-md-xray
      # Bucket base name used for image-generator and image-server applications.
      bucketBaseName: "xray-source"

main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: 0.9.*

# Example Configuration
  #datacenter:
  #  cloudProvider: aws
  #  storageClassName: gp2
  #  region: us-east-1
  #  clustername: example-sample
  #  domain: patterns.redhat.com

